# Generated by Django 3.0.5 on 2021-12-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
